services:
  stt-whisper-service:
    image: ghcr.io/sentiric/sentiric-stt-whisper-service:latest
    # --- EKLENDİ: Lokal Derleme Desteği ---
    # İmaj registry'de yoksa veya yerel geliştirme yapılıyorsa buradan derle.
    build:
      context: .
      dockerfile: Dockerfile
    # -------------------------------------
    environment:
      - STT_WHISPER_SERVICE_THREADS=8