services:
  stt-whisper-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: sentiric/stt-whisper-service:local
    # --- EKLENDİ: Yerel modelleri içeri aktar ---
    volumes:
      - ./models:/models